# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

x = 1
y = 1
z = 0
even_valued = []
while(z < 4000000):
    z = x + y
    if z % 2 == 0:
        even_valued.append(z)
    
    x = y 
    y = z

sum = sum(even_valued)
print(sum)



